# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmMain.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_frmMain(object):
    def setupUi(self, frmMain):
        frmMain.setObjectName("frmMain")
        frmMain.resize(1508, 797)
        self.leTxtSaisie = QtWidgets.QLineEdit(frmMain)
        self.leTxtSaisie.setGeometry(QtCore.QRect(30, 40, 281, 21))
        self.leTxtSaisie.setObjectName("leTxtSaisie")
        self.lstBDD = QtWidgets.QListWidget(frmMain)
        self.lstBDD.setGeometry(QtCore.QRect(30, 80, 281, 681))
        self.lstBDD.setObjectName("lstBDD")
        self.tvDatas = QtWidgets.QTableView(frmMain)
        self.tvDatas.setGeometry(QtCore.QRect(330, 40, 1161, 721))
        self.tvDatas.setStyleSheet("alternate-background-color: rgb(221, 221, 110);")
        self.tvDatas.setObjectName("tvDatas")

        self.retranslateUi(frmMain)
        QtCore.QMetaObject.connectSlotsByName(frmMain)

    def retranslateUi(self, frmMain):
        _translate = QtCore.QCoreApplication.translate
        frmMain.setWindowTitle(_translate("frmMain", "Liste des allocataires"))
